// <auto-generated />
using System;
using Anamnese.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Anamnese.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101231225_AddUserPasswordHashAndAdminSeed")]
    partial class AddUserPasswordHashAndAdminSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Anamnese.Api.Models.Access", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RoutePattern")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("HttpMethod", "RoutePattern")
                        .IsUnique();

                    b.ToTable("Accesses");
                });

            modelBuilder.Entity("Anamnese.Api.Models.Anamnesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllergiesDetails")
                        .HasColumnType("text");

                    b.Property<string>("AreaToBeRemoved")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("BloodPressureControlled")
                        .HasColumnType("boolean");

                    b.Property<string>("BreastFeedingDuration")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("DiabetesControlled")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DoesPhysicalExercise")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DrinksTwoLitersWaterDaily")
                        .HasColumnType("boolean");

                    b.Property<string>("ExOncologicStoppedWhen")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ExerciseFrequency")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateOnly?>("FormDate")
                        .HasColumnType("date");

                    b.Property<bool?>("HasAllergies")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasCirculatoryProblems")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasDermatitisAtArea")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasDiabetes")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasEpilepsy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasGlaucoma")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHansenDisease")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHemophilia")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHepatitis")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHerpes")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHiv")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHormonalProblems")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasHypertension")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasKeloidTendency")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasLupus")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasPacemaker")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasPsoriasis")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasRespiratoryProblems")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasRosacea")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasThrombosis")
                        .HasColumnType("boolean");

                    b.Property<bool?>("HasVitiligo")
                        .HasColumnType("boolean");

                    b.Property<string>("HormonalProblemsDetails")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("InCancerTreatment")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsBreastFeeding")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsExOncologicPatient")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPregnant")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSmoker")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RegularMedicationDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("RespiratoryProblemsDetails")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SignatureCity")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("SignatureDataUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("UsedInjectableLast30DaysInArea")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UsedIsotretinoinLast6Months")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UsesAcidCream")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UsesHormoneOrSteroidTherapy")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UsesRegularMedication")
                        .HasColumnType("boolean");

                    b.Property<bool?>("UsesSunscreenDaily")
                        .HasColumnType("boolean");

                    b.Property<string>("WaterIntakeQuantity")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Anamneses");
                });

            modelBuilder.Entity("Anamnese.Api.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AddressStreet")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MobilePhone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Neighborhood")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Profession")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Sex")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Anamnese.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Anamnese.Api.Models.RoleAccess", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccessId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "AccessId");

                    b.HasIndex("AccessId");

                    b.ToTable("RoleAccesses");
                });

            modelBuilder.Entity("Anamnese.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Anamnese.Api.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Anamnese.Api.Models.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Anamnese.Api.Models.Anamnesis", b =>
                {
                    b.HasOne("Anamnese.Api.Models.Client", "Client")
                        .WithMany("Anamneses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Anamnese.Api.Models.RoleAccess", b =>
                {
                    b.HasOne("Anamnese.Api.Models.Access", "Access")
                        .WithMany("RoleAccesses")
                        .HasForeignKey("AccessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anamnese.Api.Models.Role", "Role")
                        .WithMany("RoleAccesses")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Access");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Anamnese.Api.Models.UserProfile", b =>
                {
                    b.HasOne("Anamnese.Api.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Anamnese.Api.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anamnese.Api.Models.UserRole", b =>
                {
                    b.HasOne("Anamnese.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Anamnese.Api.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Anamnese.Api.Models.Access", b =>
                {
                    b.Navigation("RoleAccesses");
                });

            modelBuilder.Entity("Anamnese.Api.Models.Client", b =>
                {
                    b.Navigation("Anamneses");
                });

            modelBuilder.Entity("Anamnese.Api.Models.Role", b =>
                {
                    b.Navigation("RoleAccesses");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Anamnese.Api.Models.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
